services:

  db-service:
    image: postgres:16.2-bookworm
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_DATABASE}
      interval: ${DB_HEALTHCHECK_INTERVAL}

  server-service:
    build:
      context: server-seq/
    depends_on:
      db-service:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT_INTERN}  