services:

  db-service:
    image: postgres:16.2-bookworm
    env_file:
      - .env
    command: postgres -c log_statement=all
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: ${POSTGRES_TIMEOUT}
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL}

  server-service:
    build:
      context: server/
    env_file:
      - .env
    depends_on:
      db-service:
        condition: service_healthy
    ports:
      - ${SERVER_PORT}:${SERVER_PORT_INTERN}