services:
  db-service:
    image: postgres
    environment:
      POSTGRES_USER: 'db-user'
      POSTGRES_PASSWORD: 'db-password'
      POSTGRES_DB: 'db-database'
  server-service:
    build:
      context: /server/
    depends_on:
      - db-service
    ports:
      - 8080:3000