services:

  db-service:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  server-service:
    build:
      context: server-seq/
    depends_on:
      - db-service
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT_INTERN}